DataModeling :
    SupervisedLearning :
        DecisionTree : 
        LinearRegression : 
        LogisticRegression : 
        NaiveBayesClassification : false
        RandomForest : 
        SupportVectorMachines : false
    UnsupervisedLearning :
        kMeansClustering : 
        AssociationRules : false
        ParallelLatentDirichletAllocation : false
InferentialStatistics :
    HypothesisTests : 
